def reverse_complement_dna(dna_sequence: str) -> str:
    complement_map = {
        "A": "T",
        "T": "A",
        "C": "G",
        "G": "C"
    }

    reversed_dna_sequence = dna_sequence[::-1]

    return "".join(complement_map[c] for c in reversed_dna_sequence)


def main():
    print(reverse_complement_dna(
        "TATCAATTGTCAGCGGACCTAGGGATGTCAAGAATACCCGACTGCCTCTGAACCTTAGCAATGTTATGTTCAGTCGAGCTTAGAAGTTTGCATAACTTCATCCTTCGATCACAAGATGCGTTACCGCGCCCAACTGGTTATCTCAAGTGGACGAAACGGGCTTAAGCTTATGTCCCGCGTGCCGGTTCTGGACCTTCTACCTCCGCCCAAAGACCAACAACCGTGCTATTGGCAGAATAAATGAGGAACTCCATATTACTTTACCCCAAAGATTAAGGTACAGCCGTGATGGCAAGAATTGTCTAGCCGCCACCCCATTACTCTGCTACATACCGGGCCCATGAGGAGACCCCTCGACGGCGTCGCTAGCTAACATTACACGCACCCGACGAAGAGGCCTACTATCGTGCAGAGTGGAGGTGACTAGGCTACAACAGATGACGTGTTGTCTGCCATGCTCCTATGCTACTGCGAGTATCCTCGTGGTTATTATCTACGCAGCTGGAACTGGCGTAGGACAGCTAATTCGCAAAATAAGCGGAGGACGAGCAGAAATCCCTGCAACCACGCAGGTCCATGCCCACTTACGTGTCCCCTTTCATTGTTGGAACTCGGCAGTGACTCCTATAGCATTCTGCTCGTAGTACTCGACTCTCGTGCGAAACGGGCAAGTATTTGGTACACGCGCAGTCGCGAGGTCTTGATCTTCAACCCGCCGCCGGGGAGGTAGCCGTAGACTTGGATCCCCAGTCCCGCTTTCGTCTCTGCGGAACTGGTCTAACTGTGGTTCTCTGAGCTGGACCACTTTCGAACCTGATGGGGCGGCAAGTAGTAACTCGATATAGCTAACCAAAGTAAACGGCCAAATACCCCCTAGTTATATGTCACTGGAGTAAAGCCATGGTTCATTAGAGACGTCGAGTAGACCTGGATTGGCACACGATTTAACCAGCAAAGTTGTGT"))


if __name__ == '__main__':
    main()
